// Level data stores each state's path in absolute board-canvas coordinates
// (so a "placed" piece can reuse it as-is inside the board SVG). A tray
// piece needs the same shape translated to its own small local origin.
// The `d` strings are generated by scripts/build_usa_level.js and only
// ever contain "M x,y L x,y ... Z" tokens with plain decimal numbers, so a
// simple coordinate-pair regex is enough — no general path parser needed.
const COORD_PAIR = /(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/g;

export function translatePath(d, offX, offY) {
  return d.replace(COORD_PAIR, (_, x, y) => `${(+x - offX).toFixed(1)},${(+y - offY).toFixed(1)}`);
}
