// Auto-generated by scripts/build_usa_places.js — projects a curated list
// of famous US landmarks with the exact same Albers projection +
// normalization (and AK/HI insets) as scripts/build_usa_level.js /
// build_usa_cities.js, so these line up with levels/usa.js.
// Regenerate: node scripts/build_usa_places.js
export default [
  { id: 'golden_gate_bridge', name: 'Golden Gate Bridge', ru: 'Мост Золотые Ворота', cx: 34, cy: 269.3, radiusKm: 2 },
  { id: 'statue_of_liberty', name: 'Statue of Liberty', ru: 'Статуя Свободы', cx: 888.1, cy: 224.6, radiusKm: 2 },
  { id: 'mount_rushmore', name: 'Mount Rushmore', ru: 'Гора Рашмор', cx: 384.3, cy: 189.3, radiusKm: 2 },
  { id: 'white_house', name: 'The White House', ru: 'Белый дом', cx: 845.4, cy: 276.9, radiusKm: 2 },
  { id: 'area_51', name: 'Area 51', ru: 'Зона 51', cx: 148.9, cy: 311.8, radiusKm: 2 },
  { id: 'hollywood_sign', name: 'Hollywood Sign', ru: 'Знак Голливуд', cx: 86.9, cy: 372.4, radiusKm: 2 },
  { id: 'kennedy_space_center', name: 'Kennedy Space Center', ru: 'Космический центр Кеннеди', cx: 820.6, cy: 526.4, radiusKm: 2 },
  { id: 'harvard_university', name: 'Harvard University', ru: 'Гарвардский университет', cx: 927.4, cy: 174, radiusKm: 2 },
  { id: 'grand_canyon', name: 'Grand Canyon', ru: 'Гранд-Каньон', cx: 210.6, cy: 350.7, radiusKm: 2 },
  { id: 'yellowstone', name: 'Yellowstone National Park', ru: 'Йеллоустоунский парк', cx: 268.3, cy: 162.9, radiusKm: 2 },
  { id: 'death_valley', name: 'Death Valley', ru: 'Долина Смерти', cx: 124.9, cy: 323.6, radiusKm: 2 },
  { id: 'niagara_falls', name: 'Niagara Falls', ru: 'Ниагарский водопад', cx: 792.8, cy: 186.9, radiusKm: 2 },
  { id: 'everglades', name: 'Everglades', ru: 'Эверглейдс', cx: 827.5, cy: 602, radiusKm: 2 },
  { id: 'mauna_kea', name: 'Mauna Kea', ru: 'Мауна-Кеа', cx: 391.7, cy: 761.4, radiusKm: 2 },
  { id: 'camp_walden', name: 'Camp Walden', ru: 'Лагерь Уолден', cx: 924.4, cy: 123.5, radiusKm: 2 },
  { id: 'forks', name: 'Forks', ru: 'Форкс', cx: 70.2, cy: 33.9, radiusKm: 2 },
  { id: 'alcatraz', name: 'Alcatraz', ru: 'Алькатрас', cx: 35, cy: 269.5, radiusKm: 2 },
  { id: 'overlook_hotel', name: 'The Overlook Hotel', ru: 'Отель «Оверлук»', cx: 341.9, cy: 267.6, radiusKm: 2 },
  { id: 'bermuda_triangle', name: 'Bermuda Triangle', ru: 'Бермудский треугольник', cx: 1034.6, cy: 564.4, radiusKm: 2 },
  { id: 'las_vegas_strip', name: 'The Las Vegas Strip', ru: 'Лас-Вегас-Стрип', cx: 154.7, cy: 340, radiusKm: 2 },
];
