// Auto-generated by scripts/build_usa_places.js — projects a curated list
// of famous US landmarks with the exact same Albers projection +
// normalization (and AK/HI insets) as scripts/build_usa_level.js /
// build_usa_cities.js, so these line up with levels/usa.js.
// Regenerate: node scripts/build_usa_places.js
export default [
  { id: 'golden_gate_bridge', name: 'Golden Gate Bridge', ru: 'Мост Золотые Ворота', cx: 875.7, cy: 969.8, radiusKm: 2 },
  { id: 'statue_of_liberty', name: 'Statue of Liberty', ru: 'Статуя Свободы', cx: 1729.8, cy: 925.1, radiusKm: 2 },
  { id: 'mount_rushmore', name: 'Mount Rushmore', ru: 'Гора Рашмор', cx: 1226, cy: 889.7, radiusKm: 2 },
  { id: 'white_house', name: 'The White House', ru: 'Белый дом', cx: 1687.1, cy: 977.3, radiusKm: 2 },
  { id: 'area_51', name: 'Area 51', ru: 'Зона 51', cx: 990.6, cy: 1012.3, radiusKm: 2 },
  { id: 'norad_cheyenne_mountain', name: 'NORAD Cheyenne Mountain Complex', ru: 'НОРАД (комплекс в горе Шайенн)', cx: 1191.8, cy: 1007.3, radiusKm: 2 },
  { id: 'hollywood_sign', name: 'Hollywood Sign', ru: 'Знак Голливуд', cx: 928.6, cy: 1072.9, radiusKm: 2 },
  { id: 'kennedy_space_center', name: 'Kennedy Space Center', ru: 'Космический центр Кеннеди', cx: 1662.3, cy: 1226.8, radiusKm: 2 },
  { id: 'harvard_university', name: 'Harvard University', ru: 'Гарвардский университет', cx: 1769.1, cy: 874.5, radiusKm: 2 },
  { id: 'grand_canyon', name: 'Grand Canyon', ru: 'Гранд-Каньон', cx: 1052.3, cy: 1051.1, radiusKm: 2 },
  { id: 'yellowstone', name: 'Yellowstone National Park', ru: 'Йеллоустоунский парк', cx: 1110, cy: 863.3, radiusKm: 2 },
  { id: 'death_valley', name: 'Death Valley', ru: 'Долина Смерти', cx: 966.6, cy: 1024.1, radiusKm: 2 },
  { id: 'niagara_falls', name: 'Niagara Falls', ru: 'Ниагарский водопад', cx: 1634.5, cy: 887.4, radiusKm: 2 },
  { id: 'everglades', name: 'Everglades', ru: 'Эверглейдс', cx: 1669.3, cy: 1302.5, radiusKm: 2 },
  { id: 'mauna_kea', name: 'Mauna Kea', ru: 'Мауна-Кеа', cx: 114.5, cy: 1020.8, radiusKm: 2 },
  { id: 'camp_walden', name: 'Camp Walden', ru: 'Лагерь Уолден', cx: 1766.1, cy: 824, radiusKm: 2 },
  { id: 'forks', name: 'Forks', ru: 'Форкс', cx: 912, cy: 734.3, radiusKm: 2 },
  { id: 'alcatraz', name: 'Alcatraz', ru: 'Алькатрас', cx: 876.7, cy: 969.9, radiusKm: 2 },
  { id: 'overlook_hotel', name: 'The Overlook Hotel', ru: 'Отель «Оверлук»', cx: 1183.6, cy: 968, radiusKm: 2 },
  { id: 'bermuda_triangle', name: 'Bermuda Triangle', ru: 'Бермудский треугольник', cx: 1876.3, cy: 1264.9, radiusKm: 2 },
  { id: 'las_vegas_strip', name: 'The Las Vegas Strip', ru: 'Лас-Вегас-Стрип', cx: 996.5, cy: 1040.5, radiusKm: 2 },
  { id: 'pando', name: 'Pando', ru: 'Пандо', cx: 1068.3, cy: 996.4, radiusKm: 2 },
];
