// Auto-generated by scripts/build_usa_places.js — projects a curated list
// of famous US landmarks with the exact same Albers projection +
// normalization (and AK/HI insets) as scripts/build_usa_level.js /
// build_usa_cities.js, so these line up with levels/usa.js.
// Regenerate: node scripts/build_usa_places.js
export default [
  { id: 'golden_gate_bridge', name: 'Golden Gate Bridge', ru: 'Мост Золотые Ворота', cx: 19, cy: 254.3, radiusKm: 2 },
  { id: 'statue_of_liberty', name: 'Statue of Liberty', ru: 'Статуя Свободы', cx: 873.1, cy: 209.6, radiusKm: 2 },
  { id: 'mount_rushmore', name: 'Mount Rushmore', ru: 'Гора Рашмор', cx: 369.3, cy: 174.3, radiusKm: 2 },
  { id: 'white_house', name: 'The White House', ru: 'Белый дом', cx: 830.4, cy: 261.9, radiusKm: 2 },
  { id: 'area_51', name: 'Area 51', ru: 'Зона 51', cx: 133.9, cy: 296.8, radiusKm: 2 },
  { id: 'norad_cheyenne_mountain', name: 'NORAD Cheyenne Mountain Complex', ru: 'НОРАД (комплекс в горе Шайенн)', cx: 335.1, cy: 291.9, radiusKm: 2 },
  { id: 'hollywood_sign', name: 'Hollywood Sign', ru: 'Знак Голливуд', cx: 71.9, cy: 357.4, radiusKm: 2 },
  { id: 'kennedy_space_center', name: 'Kennedy Space Center', ru: 'Космический центр Кеннеди', cx: 805.6, cy: 511.4, radiusKm: 2 },
  { id: 'harvard_university', name: 'Harvard University', ru: 'Гарвардский университет', cx: 912.4, cy: 159, radiusKm: 2 },
  { id: 'grand_canyon', name: 'Grand Canyon', ru: 'Гранд-Каньон', cx: 195.6, cy: 335.7, radiusKm: 2 },
  { id: 'yellowstone', name: 'Yellowstone National Park', ru: 'Йеллоустоунский парк', cx: 253.3, cy: 147.9, radiusKm: 2 },
  { id: 'death_valley', name: 'Death Valley', ru: 'Долина Смерти', cx: 109.9, cy: 308.6, radiusKm: 2 },
  { id: 'niagara_falls', name: 'Niagara Falls', ru: 'Ниагарский водопад', cx: 777.8, cy: 171.9, radiusKm: 2 },
  { id: 'everglades', name: 'Everglades', ru: 'Эверглейдс', cx: 812.5, cy: 587, radiusKm: 2 },
  { id: 'mauna_kea', name: 'Mauna Kea', ru: 'Мауна-Кеа', cx: 391.7, cy: 761.4, radiusKm: 2 },
  { id: 'camp_walden', name: 'Camp Walden', ru: 'Лагерь Уолден', cx: 909.4, cy: 108.5, radiusKm: 2 },
  { id: 'forks', name: 'Forks', ru: 'Форкс', cx: 55.2, cy: 18.9, radiusKm: 2 },
  { id: 'alcatraz', name: 'Alcatraz', ru: 'Алькатрас', cx: 20, cy: 254.5, radiusKm: 2 },
  { id: 'overlook_hotel', name: 'The Overlook Hotel', ru: 'Отель «Оверлук»', cx: 326.9, cy: 252.6, radiusKm: 2 },
  { id: 'bermuda_triangle', name: 'Bermuda Triangle', ru: 'Бермудский треугольник', cx: 1019.6, cy: 549.4, radiusKm: 2 },
  { id: 'las_vegas_strip', name: 'The Las Vegas Strip', ru: 'Лас-Вегас-Стрип', cx: 139.7, cy: 325, radiusKm: 2 },
];
