// Auto-generated by scripts/build_usa_route_graph.js from levels/usa.js's
// state polygons/neighbors and levels/usaHighways.js's route geometry.
// See the build script's own comments for the ordering algorithm
// (real shared-border adjacency, falling back to a PCA-projection
// approximation for routes whose touched-state set isn't a clean chain).
// Regenerate: node scripts/build_usa_route_graph.js
export default {
  "routeStates": {
    "i2": [
      "TX"
    ],
    "i4": [
      "FL"
    ],
    "i5": [
      "CA",
      "OR",
      "WA"
    ],
    "i8": [
      "CA",
      "AZ"
    ],
    "i10": [
      "CA",
      "AZ",
      "NM",
      "TX",
      "LA",
      "MS",
      "AL",
      "FL"
    ],
    "i11": [
      "NV"
    ],
    "i12": [
      "LA"
    ],
    "i14": [
      "TX"
    ],
    "i15": [
      "CA",
      "NV",
      "AZ",
      "UT",
      "ID",
      "MT"
    ],
    "i16": [
      "GA"
    ],
    "i17": [
      "AZ"
    ],
    "i19": [
      "AZ"
    ],
    "i20": [
      "TX",
      "LA",
      "MS",
      "AL",
      "GA",
      "SC"
    ],
    "i22": [
      "MS",
      "AL"
    ],
    "i24": [
      "IL",
      "KY",
      "TN",
      "GA"
    ],
    "i25": [
      "NM",
      "CO",
      "WY"
    ],
    "i26": [
      "SC",
      "NC",
      "TN"
    ],
    "i27": [
      "TX"
    ],
    "i29": [
      "ND",
      "SD",
      "NE",
      "IA",
      "MO"
    ],
    "i30": [
      "TX",
      "AR"
    ],
    "i35": [
      "TX",
      "OK",
      "KS",
      "MO",
      "IA",
      "MN"
    ],
    "i37": [
      "TX"
    ],
    "i39": [
      "IL",
      "WI"
    ],
    "i40": [
      "CA",
      "AZ",
      "NM",
      "TX",
      "OK",
      "AR",
      "TN",
      "NC"
    ],
    "i41": [
      "WI",
      "IL"
    ],
    "i43": [
      "WI"
    ],
    "i44": [
      "IL",
      "MO",
      "OK",
      "TX"
    ],
    "i45": [
      "TX"
    ],
    "i49-a": [
      "TX",
      "AR",
      "LA"
    ],
    "i49-b": [
      "MO",
      "AR"
    ],
    "i55": [
      "LA",
      "MS",
      "TN",
      "AR",
      "MO",
      "IL"
    ],
    "i57": [
      "IL",
      "MO"
    ],
    "i59": [
      "GA",
      "AL",
      "MS",
      "LA"
    ],
    "i64": [
      "MO",
      "IL",
      "IN",
      "KY",
      "WV",
      "VA"
    ],
    "i65": [
      "IN",
      "KY",
      "TN",
      "AL"
    ],
    "i66": [
      "VA"
    ],
    "i68": [
      "MD",
      "WV"
    ],
    "i69-a": [
      "KY",
      "IN",
      "MI"
    ],
    "i69-b": [
      "TX"
    ],
    "i69-c": [
      "MS"
    ],
    "i69-d": [
      "TX"
    ],
    "i70": [
      "UT",
      "CO",
      "KS",
      "MO",
      "IL",
      "IN",
      "OH",
      "WV",
      "PA",
      "MD"
    ],
    "i71": [
      "OH",
      "KY"
    ],
    "i72": [
      "IL",
      "MO"
    ],
    "i73": [
      "NC"
    ],
    "i74-a": [
      "IA",
      "IL",
      "IN",
      "OH"
    ],
    "i74-b": [
      "NC"
    ],
    "i75": [
      "MI",
      "OH",
      "KY",
      "TN",
      "GA",
      "FL"
    ],
    "i76-a": [
      "NJ",
      "PA",
      "OH"
    ],
    "i76-b": [
      "CO",
      "NE"
    ],
    "i77": [
      "OH",
      "WV",
      "VA",
      "NC",
      "SC"
    ],
    "i78": [
      "PA",
      "NJ",
      "NY"
    ],
    "i79": [
      "PA",
      "WV"
    ],
    "i80": [
      "CA",
      "NV",
      "UT",
      "WY",
      "NE",
      "IA",
      "IL",
      "IN",
      "OH",
      "PA",
      "NJ"
    ],
    "i81": [
      "TN",
      "VA",
      "WV",
      "MD",
      "PA",
      "NY"
    ],
    "i82": [
      "WA",
      "OR"
    ],
    "i83": [
      "PA",
      "MD"
    ],
    "i84-a": [
      "WA",
      "OR",
      "ID",
      "UT"
    ],
    "i84-b": [
      "PA",
      "NJ",
      "NY",
      "CT",
      "MA"
    ],
    "i85": [
      "AL",
      "GA",
      "SC",
      "NC",
      "VA"
    ],
    "i86-a": [
      "NY",
      "PA"
    ],
    "i86-b": [
      "ID"
    ],
    "i87": [
      "NY"
    ],
    "i88-a": [
      "NY"
    ],
    "i88-b": [
      "IL"
    ],
    "i89": [
      "VT",
      "NH"
    ],
    "i90": [
      "WA",
      "ID",
      "MT",
      "WY",
      "SD",
      "MN",
      "WI",
      "IL",
      "IN",
      "OH",
      "PA",
      "NY",
      "MA"
    ],
    "i91": [
      "VT",
      "NH",
      "MA",
      "CT"
    ],
    "i93": [
      "VT",
      "NH",
      "MA"
    ],
    "i94": [
      "MT",
      "ND",
      "MN",
      "WI",
      "IL",
      "IN",
      "MI"
    ],
    "i95": [
      "FL",
      "GA",
      "SC",
      "NC",
      "VA",
      "MD",
      "DE",
      "PA",
      "NJ",
      "NY",
      "CT",
      "RI",
      "MA",
      "NH",
      "ME"
    ],
    "i96": [
      "MI"
    ],
    "i97": [
      "MD"
    ],
    "i99": [
      "PA",
      "NY"
    ]
  },
  "adjacency": {
    "CA": [
      {
        "to": "OR",
        "routeId": "i5",
        "routeNumber": "5",
        "baseRouteId": "i5"
      },
      {
        "to": "AZ",
        "routeId": "i8",
        "routeNumber": "8",
        "baseRouteId": "i8"
      },
      {
        "to": "AZ",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "NV",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "AZ",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "NV",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      }
    ],
    "OR": [
      {
        "to": "CA",
        "routeId": "i5",
        "routeNumber": "5",
        "baseRouteId": "i5"
      },
      {
        "to": "WA",
        "routeId": "i5",
        "routeNumber": "5",
        "baseRouteId": "i5"
      },
      {
        "to": "WA",
        "routeId": "i82",
        "routeNumber": "82",
        "baseRouteId": "i82"
      },
      {
        "to": "WA",
        "routeId": "i84-a",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "ID",
        "routeId": "i84-a",
        "routeNumber": "84",
        "baseRouteId": "i84"
      }
    ],
    "WA": [
      {
        "to": "OR",
        "routeId": "i5",
        "routeNumber": "5",
        "baseRouteId": "i5"
      },
      {
        "to": "OR",
        "routeId": "i82",
        "routeNumber": "82",
        "baseRouteId": "i82"
      },
      {
        "to": "OR",
        "routeId": "i84-a",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "ID",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      }
    ],
    "AZ": [
      {
        "to": "CA",
        "routeId": "i8",
        "routeNumber": "8",
        "baseRouteId": "i8"
      },
      {
        "to": "CA",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "NM",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "NV",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "UT",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "CA",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "NM",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      }
    ],
    "NM": [
      {
        "to": "AZ",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "TX",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "CO",
        "routeId": "i25",
        "routeNumber": "25",
        "baseRouteId": "i25"
      },
      {
        "to": "AZ",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "TX",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      }
    ],
    "TX": [
      {
        "to": "NM",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "LA",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "LA",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "AR",
        "routeId": "i30",
        "routeNumber": "30",
        "baseRouteId": "i30"
      },
      {
        "to": "OK",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "NM",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "OK",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "OK",
        "routeId": "i44",
        "routeNumber": "44",
        "baseRouteId": "i44"
      },
      {
        "to": "AR",
        "routeId": "i49-a",
        "routeNumber": "49",
        "baseRouteId": "i49"
      }
    ],
    "LA": [
      {
        "to": "TX",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "MS",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "TX",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "MS",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "AR",
        "routeId": "i49-a",
        "routeNumber": "49",
        "baseRouteId": "i49"
      },
      {
        "to": "MS",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "MS",
        "routeId": "i59",
        "routeNumber": "59",
        "baseRouteId": "i59"
      }
    ],
    "MS": [
      {
        "to": "LA",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "AL",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "LA",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "AL",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "AL",
        "routeId": "i22",
        "routeNumber": "22",
        "baseRouteId": "i22"
      },
      {
        "to": "LA",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "TN",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "AL",
        "routeId": "i59",
        "routeNumber": "59",
        "baseRouteId": "i59"
      },
      {
        "to": "LA",
        "routeId": "i59",
        "routeNumber": "59",
        "baseRouteId": "i59"
      }
    ],
    "AL": [
      {
        "to": "MS",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "FL",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "MS",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "GA",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "MS",
        "routeId": "i22",
        "routeNumber": "22",
        "baseRouteId": "i22"
      },
      {
        "to": "GA",
        "routeId": "i59",
        "routeNumber": "59",
        "baseRouteId": "i59"
      },
      {
        "to": "MS",
        "routeId": "i59",
        "routeNumber": "59",
        "baseRouteId": "i59"
      },
      {
        "to": "TN",
        "routeId": "i65",
        "routeNumber": "65",
        "baseRouteId": "i65"
      },
      {
        "to": "GA",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      }
    ],
    "FL": [
      {
        "to": "AL",
        "routeId": "i10",
        "routeNumber": "10",
        "baseRouteId": "i10"
      },
      {
        "to": "GA",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "GA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "NV": [
      {
        "to": "CA",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "AZ",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "CA",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "UT",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      }
    ],
    "UT": [
      {
        "to": "AZ",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "ID",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "CO",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "NV",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "WY",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "ID",
        "routeId": "i84-a",
        "routeNumber": "84",
        "baseRouteId": "i84"
      }
    ],
    "ID": [
      {
        "to": "UT",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "MT",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "OR",
        "routeId": "i84-a",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "UT",
        "routeId": "i84-a",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "WA",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "MT",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      }
    ],
    "MT": [
      {
        "to": "ID",
        "routeId": "i15",
        "routeNumber": "15",
        "baseRouteId": "i15"
      },
      {
        "to": "ID",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "WY",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "ND",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "GA": [
      {
        "to": "AL",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "SC",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "TN",
        "routeId": "i24",
        "routeNumber": "24",
        "baseRouteId": "i24"
      },
      {
        "to": "AL",
        "routeId": "i59",
        "routeNumber": "59",
        "baseRouteId": "i59"
      },
      {
        "to": "TN",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "FL",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "AL",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "SC",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "FL",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "SC",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "SC": [
      {
        "to": "GA",
        "routeId": "i20",
        "routeNumber": "20",
        "baseRouteId": "i20"
      },
      {
        "to": "NC",
        "routeId": "i26",
        "routeNumber": "26",
        "baseRouteId": "i26"
      },
      {
        "to": "NC",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "GA",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "NC",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "GA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "NC",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "IL": [
      {
        "to": "KY",
        "routeId": "i24",
        "routeNumber": "24",
        "baseRouteId": "i24"
      },
      {
        "to": "WI",
        "routeId": "i39",
        "routeNumber": "39",
        "baseRouteId": "i39"
      },
      {
        "to": "WI",
        "routeId": "i41",
        "routeNumber": "41",
        "baseRouteId": "i41"
      },
      {
        "to": "MO",
        "routeId": "i44",
        "routeNumber": "44",
        "baseRouteId": "i44"
      },
      {
        "to": "MO",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "MO",
        "routeId": "i57",
        "routeNumber": "57",
        "baseRouteId": "i57"
      },
      {
        "to": "MO",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "IN",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "MO",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "IN",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "MO",
        "routeId": "i72",
        "routeNumber": "72",
        "baseRouteId": "i72"
      },
      {
        "to": "IA",
        "routeId": "i74-a",
        "routeNumber": "74",
        "baseRouteId": "i74"
      },
      {
        "to": "IN",
        "routeId": "i74-a",
        "routeNumber": "74",
        "baseRouteId": "i74"
      },
      {
        "to": "IA",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "IN",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "WI",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "IN",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "WI",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      },
      {
        "to": "IN",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "KY": [
      {
        "to": "IL",
        "routeId": "i24",
        "routeNumber": "24",
        "baseRouteId": "i24"
      },
      {
        "to": "TN",
        "routeId": "i24",
        "routeNumber": "24",
        "baseRouteId": "i24"
      },
      {
        "to": "IN",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "WV",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "IN",
        "routeId": "i65",
        "routeNumber": "65",
        "baseRouteId": "i65"
      },
      {
        "to": "TN",
        "routeId": "i65",
        "routeNumber": "65",
        "baseRouteId": "i65"
      },
      {
        "to": "IN",
        "routeId": "i69-a",
        "routeNumber": "69",
        "baseRouteId": "i69"
      },
      {
        "to": "OH",
        "routeId": "i71",
        "routeNumber": "71",
        "baseRouteId": "i71"
      },
      {
        "to": "OH",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "TN",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      }
    ],
    "TN": [
      {
        "to": "KY",
        "routeId": "i24",
        "routeNumber": "24",
        "baseRouteId": "i24"
      },
      {
        "to": "GA",
        "routeId": "i24",
        "routeNumber": "24",
        "baseRouteId": "i24"
      },
      {
        "to": "NC",
        "routeId": "i26",
        "routeNumber": "26",
        "baseRouteId": "i26"
      },
      {
        "to": "AR",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "NC",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "MS",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "AR",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "KY",
        "routeId": "i65",
        "routeNumber": "65",
        "baseRouteId": "i65"
      },
      {
        "to": "AL",
        "routeId": "i65",
        "routeNumber": "65",
        "baseRouteId": "i65"
      },
      {
        "to": "KY",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "GA",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "VA",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      }
    ],
    "CO": [
      {
        "to": "NM",
        "routeId": "i25",
        "routeNumber": "25",
        "baseRouteId": "i25"
      },
      {
        "to": "WY",
        "routeId": "i25",
        "routeNumber": "25",
        "baseRouteId": "i25"
      },
      {
        "to": "UT",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "KS",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "NE",
        "routeId": "i76-b",
        "routeNumber": "76",
        "baseRouteId": "i76"
      }
    ],
    "WY": [
      {
        "to": "CO",
        "routeId": "i25",
        "routeNumber": "25",
        "baseRouteId": "i25"
      },
      {
        "to": "UT",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "NE",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "MT",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "SD",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      }
    ],
    "NC": [
      {
        "to": "SC",
        "routeId": "i26",
        "routeNumber": "26",
        "baseRouteId": "i26"
      },
      {
        "to": "TN",
        "routeId": "i26",
        "routeNumber": "26",
        "baseRouteId": "i26"
      },
      {
        "to": "TN",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "VA",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "SC",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "SC",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "VA",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "SC",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "VA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "ND": [
      {
        "to": "SD",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "MT",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      },
      {
        "to": "MN",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "SD": [
      {
        "to": "ND",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "NE",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "WY",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "MN",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      }
    ],
    "NE": [
      {
        "to": "SD",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "IA",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "CO",
        "routeId": "i76-b",
        "routeNumber": "76",
        "baseRouteId": "i76"
      },
      {
        "to": "WY",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "IA",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      }
    ],
    "IA": [
      {
        "to": "NE",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "MO",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "MO",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "MN",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "IL",
        "routeId": "i74-a",
        "routeNumber": "74",
        "baseRouteId": "i74"
      },
      {
        "to": "NE",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "IL",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      }
    ],
    "MO": [
      {
        "to": "IA",
        "routeId": "i29",
        "routeNumber": "29",
        "baseRouteId": "i29"
      },
      {
        "to": "KS",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "IA",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "IL",
        "routeId": "i44",
        "routeNumber": "44",
        "baseRouteId": "i44"
      },
      {
        "to": "OK",
        "routeId": "i44",
        "routeNumber": "44",
        "baseRouteId": "i44"
      },
      {
        "to": "AR",
        "routeId": "i49-b",
        "routeNumber": "49",
        "baseRouteId": "i49"
      },
      {
        "to": "AR",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "IL",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "IL",
        "routeId": "i57",
        "routeNumber": "57",
        "baseRouteId": "i57"
      },
      {
        "to": "IL",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "KS",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "IL",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "IL",
        "routeId": "i72",
        "routeNumber": "72",
        "baseRouteId": "i72"
      }
    ],
    "AR": [
      {
        "to": "TX",
        "routeId": "i30",
        "routeNumber": "30",
        "baseRouteId": "i30"
      },
      {
        "to": "OK",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "TN",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "TX",
        "routeId": "i49-a",
        "routeNumber": "49",
        "baseRouteId": "i49"
      },
      {
        "to": "LA",
        "routeId": "i49-a",
        "routeNumber": "49",
        "baseRouteId": "i49"
      },
      {
        "to": "MO",
        "routeId": "i49-b",
        "routeNumber": "49",
        "baseRouteId": "i49"
      },
      {
        "to": "TN",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      },
      {
        "to": "MO",
        "routeId": "i55",
        "routeNumber": "55",
        "baseRouteId": "i55"
      }
    ],
    "OK": [
      {
        "to": "TX",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "KS",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "TX",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "AR",
        "routeId": "i40",
        "routeNumber": "40",
        "baseRouteId": "i40"
      },
      {
        "to": "MO",
        "routeId": "i44",
        "routeNumber": "44",
        "baseRouteId": "i44"
      },
      {
        "to": "TX",
        "routeId": "i44",
        "routeNumber": "44",
        "baseRouteId": "i44"
      }
    ],
    "KS": [
      {
        "to": "OK",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "MO",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "CO",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "MO",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      }
    ],
    "MN": [
      {
        "to": "IA",
        "routeId": "i35",
        "routeNumber": "35",
        "baseRouteId": "i35"
      },
      {
        "to": "SD",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "WI",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "ND",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      },
      {
        "to": "WI",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "WI": [
      {
        "to": "IL",
        "routeId": "i39",
        "routeNumber": "39",
        "baseRouteId": "i39"
      },
      {
        "to": "IL",
        "routeId": "i41",
        "routeNumber": "41",
        "baseRouteId": "i41"
      },
      {
        "to": "MN",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "IL",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "MN",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      },
      {
        "to": "IL",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "IN": [
      {
        "to": "IL",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "KY",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "KY",
        "routeId": "i65",
        "routeNumber": "65",
        "baseRouteId": "i65"
      },
      {
        "to": "KY",
        "routeId": "i69-a",
        "routeNumber": "69",
        "baseRouteId": "i69"
      },
      {
        "to": "MI",
        "routeId": "i69-a",
        "routeNumber": "69",
        "baseRouteId": "i69"
      },
      {
        "to": "IL",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "OH",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "IL",
        "routeId": "i74-a",
        "routeNumber": "74",
        "baseRouteId": "i74"
      },
      {
        "to": "OH",
        "routeId": "i74-a",
        "routeNumber": "74",
        "baseRouteId": "i74"
      },
      {
        "to": "IL",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "OH",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "IL",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "OH",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "IL",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      },
      {
        "to": "MI",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "WV": [
      {
        "to": "KY",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "VA",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "MD",
        "routeId": "i68",
        "routeNumber": "68",
        "baseRouteId": "i68"
      },
      {
        "to": "OH",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "PA",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "OH",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "VA",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "PA",
        "routeId": "i79",
        "routeNumber": "79",
        "baseRouteId": "i79"
      },
      {
        "to": "VA",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "MD",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      }
    ],
    "VA": [
      {
        "to": "WV",
        "routeId": "i64",
        "routeNumber": "64",
        "baseRouteId": "i64"
      },
      {
        "to": "WV",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "NC",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "TN",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "WV",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "NC",
        "routeId": "i85",
        "routeNumber": "85",
        "baseRouteId": "i85"
      },
      {
        "to": "NC",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "MD",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "MD": [
      {
        "to": "WV",
        "routeId": "i68",
        "routeNumber": "68",
        "baseRouteId": "i68"
      },
      {
        "to": "PA",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "WV",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "PA",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "PA",
        "routeId": "i83",
        "routeNumber": "83",
        "baseRouteId": "i83"
      },
      {
        "to": "VA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "DE",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "MI": [
      {
        "to": "IN",
        "routeId": "i69-a",
        "routeNumber": "69",
        "baseRouteId": "i69"
      },
      {
        "to": "OH",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "IN",
        "routeId": "i94",
        "routeNumber": "94",
        "baseRouteId": "i94"
      }
    ],
    "OH": [
      {
        "to": "IN",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "WV",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "KY",
        "routeId": "i71",
        "routeNumber": "71",
        "baseRouteId": "i71"
      },
      {
        "to": "IN",
        "routeId": "i74-a",
        "routeNumber": "74",
        "baseRouteId": "i74"
      },
      {
        "to": "MI",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "KY",
        "routeId": "i75",
        "routeNumber": "75",
        "baseRouteId": "i75"
      },
      {
        "to": "PA",
        "routeId": "i76-a",
        "routeNumber": "76",
        "baseRouteId": "i76"
      },
      {
        "to": "WV",
        "routeId": "i77",
        "routeNumber": "77",
        "baseRouteId": "i77"
      },
      {
        "to": "IN",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "PA",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "IN",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "PA",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      }
    ],
    "PA": [
      {
        "to": "WV",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "MD",
        "routeId": "i70",
        "routeNumber": "70",
        "baseRouteId": "i70"
      },
      {
        "to": "NJ",
        "routeId": "i76-a",
        "routeNumber": "76",
        "baseRouteId": "i76"
      },
      {
        "to": "OH",
        "routeId": "i76-a",
        "routeNumber": "76",
        "baseRouteId": "i76"
      },
      {
        "to": "NJ",
        "routeId": "i78",
        "routeNumber": "78",
        "baseRouteId": "i78"
      },
      {
        "to": "WV",
        "routeId": "i79",
        "routeNumber": "79",
        "baseRouteId": "i79"
      },
      {
        "to": "OH",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "NJ",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "MD",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "NY",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "MD",
        "routeId": "i83",
        "routeNumber": "83",
        "baseRouteId": "i83"
      },
      {
        "to": "NJ",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "NY",
        "routeId": "i86-a",
        "routeNumber": "86",
        "baseRouteId": "i86"
      },
      {
        "to": "OH",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "NY",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "DE",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "NJ",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "NY",
        "routeId": "i99",
        "routeNumber": "99",
        "baseRouteId": "i99"
      }
    ],
    "NJ": [
      {
        "to": "PA",
        "routeId": "i76-a",
        "routeNumber": "76",
        "baseRouteId": "i76"
      },
      {
        "to": "PA",
        "routeId": "i78",
        "routeNumber": "78",
        "baseRouteId": "i78"
      },
      {
        "to": "NY",
        "routeId": "i78",
        "routeNumber": "78",
        "baseRouteId": "i78"
      },
      {
        "to": "PA",
        "routeId": "i80",
        "routeNumber": "80",
        "baseRouteId": "i80"
      },
      {
        "to": "PA",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "NY",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "PA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "NY",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "NY": [
      {
        "to": "NJ",
        "routeId": "i78",
        "routeNumber": "78",
        "baseRouteId": "i78"
      },
      {
        "to": "PA",
        "routeId": "i81",
        "routeNumber": "81",
        "baseRouteId": "i81"
      },
      {
        "to": "NJ",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "CT",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "PA",
        "routeId": "i86-a",
        "routeNumber": "86",
        "baseRouteId": "i86"
      },
      {
        "to": "PA",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "MA",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "NJ",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "CT",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "PA",
        "routeId": "i99",
        "routeNumber": "99",
        "baseRouteId": "i99"
      }
    ],
    "CT": [
      {
        "to": "NY",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "MA",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "MA",
        "routeId": "i91",
        "routeNumber": "91",
        "baseRouteId": "i91"
      },
      {
        "to": "NY",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "RI",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "MA": [
      {
        "to": "CT",
        "routeId": "i84-b",
        "routeNumber": "84",
        "baseRouteId": "i84"
      },
      {
        "to": "NY",
        "routeId": "i90",
        "routeNumber": "90",
        "baseRouteId": "i90"
      },
      {
        "to": "NH",
        "routeId": "i91",
        "routeNumber": "91",
        "baseRouteId": "i91"
      },
      {
        "to": "CT",
        "routeId": "i91",
        "routeNumber": "91",
        "baseRouteId": "i91"
      },
      {
        "to": "NH",
        "routeId": "i93",
        "routeNumber": "93",
        "baseRouteId": "i93"
      },
      {
        "to": "RI",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "NH",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "VT": [
      {
        "to": "NH",
        "routeId": "i89",
        "routeNumber": "89",
        "baseRouteId": "i89"
      },
      {
        "to": "NH",
        "routeId": "i91",
        "routeNumber": "91",
        "baseRouteId": "i91"
      },
      {
        "to": "NH",
        "routeId": "i93",
        "routeNumber": "93",
        "baseRouteId": "i93"
      }
    ],
    "NH": [
      {
        "to": "VT",
        "routeId": "i89",
        "routeNumber": "89",
        "baseRouteId": "i89"
      },
      {
        "to": "VT",
        "routeId": "i91",
        "routeNumber": "91",
        "baseRouteId": "i91"
      },
      {
        "to": "MA",
        "routeId": "i91",
        "routeNumber": "91",
        "baseRouteId": "i91"
      },
      {
        "to": "VT",
        "routeId": "i93",
        "routeNumber": "93",
        "baseRouteId": "i93"
      },
      {
        "to": "MA",
        "routeId": "i93",
        "routeNumber": "93",
        "baseRouteId": "i93"
      },
      {
        "to": "MA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "ME",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "DE": [
      {
        "to": "MD",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "PA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "RI": [
      {
        "to": "CT",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      },
      {
        "to": "MA",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ],
    "ME": [
      {
        "to": "NH",
        "routeId": "i95",
        "routeNumber": "95",
        "baseRouteId": "i95"
      }
    ]
  }
};
