// Builds levels/usaOutline.js — a single silhouette path covering the 48
// contiguous states with NO internal state borders, for the "Расположи
// штат" mode's gray map (see openspec/changes/state-placement-mode).
// Projected through the EXACT same Albers projection + normalization as
// scripts/build_usa_level.js/build_usa_places.js/build_usa_lakes.js, so it
// lines up with everything else on the USA canvas.
//
// Source: scripts/data/us-mainland-outline.geojson — a dissolved
// (polygon-union) MultiPolygon of the 48 states, still in real lon/lat, NOT
// projected. Regenerate that intermediate file from scratch with:
//   npx mapshaper scripts/data/us-states.geojson -filter '!["Alaska","Hawaii","District of Columbia","Puerto Rico"].includes(name)' -dissolve -o format=geojson precision=0.0001 scripts/data/us-mainland-outline.geojson
// (mapshaper's -dissolve drops the properties table and emits a bare
// GeometryCollection, not a FeatureCollection — this script reads that
// shape directly, see `geo.geometries[0]` below.)
//
// Regenerate: node scripts/build_usa_outline.js
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'data', 'us-mainland-outline.geojson');
const geo = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const geometry = geo.geometries[0];

// ---- same Albers projection as build_usa_level.js/build_usa_places.js/build_usa_lakes.js ----
const deg2rad = (d) => (d * Math.PI) / 180;
const phi1 = deg2rad(29.5);
const phi2 = deg2rad(45.5);
const phi0 = deg2rad(23);
const lambda0 = deg2rad(-96);
const n = (Math.sin(phi1) + Math.sin(phi2)) / 2;
const C = Math.cos(phi1) ** 2 + 2 * n * Math.sin(phi1);
const rho0 = Math.sqrt(C - 2 * n * Math.sin(phi0)) / n;
function albers([lon, lat]) {
  const lambda = deg2rad(lon);
  const phi = deg2rad(lat);
  const theta = n * (lambda - lambda0);
  const rho = Math.sqrt(C - 2 * n * Math.sin(phi)) / n;
  const x = rho * Math.sin(theta);
  const y = rho0 - rho * Math.cos(theta);
  return [x, -y];
}
function forEachRing(g, fn) {
  if (g.type === 'Polygon') g.coordinates.forEach((ring) => fn(ring));
  else if (g.type === 'MultiPolygon') g.coordinates.forEach((poly) => poly.forEach((ring) => fn(ring)));
}

// ---- re-derive the exact same contiguous-US bbox/scale/margin/shift as
// build_usa_places.js/build_usa_lakes.js (must match exactly) ----
const STATES_SRC = path.join(__dirname, 'data', 'us-states.geojson');
const statesGeo = JSON.parse(fs.readFileSync(STATES_SRC, 'utf8'));
const SKIP = new Set(['Puerto Rico', 'District of Columbia', 'Alaska', 'Hawaii']);
let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
for (const f of statesGeo.features) {
  if (SKIP.has(f.properties.name)) continue;
  forEachRing(f.geometry, (ring) => {
    for (const pt of ring.map(albers)) {
      const [x, y] = pt;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  });
}
const TARGET_W = 960;
const scale = TARGET_W / (maxX - minX);
const MARGIN = 3;
const GLOBAL_SHIFT_X = 856.7122654651434;
const GLOBAL_SHIFT_Y = 636.0468616448984;
function toCanvasMain([lon, lat]) {
  const [x, y] = albers([lon, lat]);
  return [(x - minX) * scale + MARGIN + GLOBAL_SHIFT_X, (y - minY) * scale + MARGIN + GLOBAL_SHIFT_Y];
}

function ringToPath(ring) {
  return (
    'M ' +
    ring
      .map((pt) => {
        const [x, y] = toCanvasMain(pt);
        return `${x.toFixed(2)},${y.toFixed(2)}`;
      })
      .join(' L ') +
    ' Z'
  );
}
function geometryToPath(g) {
  if (g.type === 'Polygon') return g.coordinates.map(ringToPath).join(' ');
  if (g.type === 'MultiPolygon') return g.coordinates.map((poly) => poly.map(ringToPath).join(' ')).join(' ');
  return '';
}
function geometryBbox(g) {
  let bx0 = Infinity, by0 = Infinity, bx1 = -Infinity, by1 = -Infinity;
  forEachRing(g, (ring) => {
    for (const pt of ring) {
      const [x, y] = toCanvasMain(pt);
      if (x < bx0) bx0 = x;
      if (x > bx1) bx1 = x;
      if (y < by0) by0 = y;
      if (y > by1) by1 = y;
    }
  });
  return [bx0, by0, bx1, by1];
}

const d = geometryToPath(geometry);
const bbox = geometryBbox(geometry).map((v) => +v.toFixed(1));

console.error('outline bbox:', bbox);
console.error('path length (chars):', d.length);

let out = `// Auto-generated by scripts/build_usa_outline.js — a single silhouette\n`;
out += `// path covering the 48 contiguous states with NO internal state borders,\n`;
out += `// projected with the exact same Albers projection + normalization as\n`;
out += `// scripts/build_usa_level.js, so it lines up with levels/usa.js.\n`;
out += `// Regenerate: node scripts/build_usa_outline.js\n`;
out += `export default {\n`;
out += `  bbox: [${bbox.join(', ')}],\n`;
out += `  d: '${d}',\n`;
out += `};\n`;

const outPath = path.join(__dirname, '..', 'levels', 'usaOutline.js');
fs.writeFileSync(outPath, out, 'utf8');
console.error('wrote', outPath, out.length, 'bytes');
